In [1]:
# La funcion filter sobre diccionarios

# Consideremos un diccionario  de datos
data1 = {"A":19, "B":2, "C":14, "D":1, "E":5}

dict(filter(lambda x:x[1]>12 , data1.items()))

{'A': 19, 'C': 14}

In [2]:
# Recuperemos de data1 aquellos valores cuya llave es "B"
dict(filter(lambda x:x[0]=="B", data1.items()))

{'B': 2}

In [4]:
# La funcion map sobre diccionarios

# Multipliquemos por un aleatorio a cada valor del diccionario data1
import random as rnd
dict(map(lambda x:(x[0] + str(rnd.randint(1,2)), x[1]*rnd.randint(0,5)) , data1.items()))

{'A2': 76, 'B2': 4, 'C1': 28, 'D2': 3, 'E1': 10}

In [5]:
# Reduce para diccionarios

# Calculemos la suma de todos los valores de data1
from functools import reduce
reduce(lambda x,y:x + y[1], data1.items(), 0)

41

# Funcion zip
* Sirve para reorganizar listas
* Como parametros admite un conjunto de listas
* lo que hace es tomar el elemento i-esimo de cada lista y unirlos en una tupla, despues une todas las tuplas en una sola lista

In [7]:
# Punto de partida : dos listas
# COnsideremos una lista de nombres y otra de sus correspondientes apellidos
# Vamos a usar zip

# Definamos las listas / tuplas
ListaName1 = ("Adrian", "Jorge", "Alejandra", "Andrea", "Marta")
ListaApellidosPat = ("Luna", "Torres", "Arambulo", "Cernades", "Echegaray")

# zip usa cada nombre con su correspondiente apellido y los empaqueta en una tupla
NombreApellido = list(zip(ListaName1, ListaApellidosPat))
NombreApellido

[('Adrian', 'Luna'),
 ('Jorge', 'Torres'),
 ('Alejandra', 'Arambulo'),
 ('Andrea', 'Cernades'),
 ('Marta', 'Echegaray')]